name: Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create env file'
        run: |
          touch .env
          echo REACT_APP_SOLANA_RPC_HOST="https://devnet.helius-rpc.com/?api-key=72240cfd-923b-4743-a9d8-b1fdeae41313" >> .env
          echo REACT_APP_NETWORK="devnet" >> .env
          cat .env
      - uses: actions/checkout@v2
      - uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v2
        with:
          node-version: "22"
      - run: yarn install
      - name: Build
        run: yarn build
